# Generated by Django 3.0.8 on 2020-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timestamp_of_imdb', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
